---
# 配置文件请严格遵循yaml语法格式，yaml学习地址 https://ansible-tran.readthedocs.io/en/latest/docs/YAMLSyntax.html
set:
  # 出发日期(list)，格式ex：
  # - 2018-01-06
  # - 2018-01-07
  station_dates:
    - "2019-01-18"

  # 是否根据时间范围 和 乘车类型 购票
  # 否则将需要手动填写车次
  is_by_time: False

  # 列车类型: 高铁 G 动车 D 其它火车 O
  train_types: [G,D,O]

  # 可接受最早出发时间 格式ex：
  # departure_time: "8:00"
  departure_time: "00:00"

  # 可接受最晚抵达时间 格式ex：
  # arrival_time: "16:00"
  arrival_time: "24:00"

  # 可接受最长旅途时间 格式ex：
  # take_time: "24:00"
  take_time: "24:00"

  # 填入需要购买的车次(list)，格式ex：
  # - "G1353"
  # - "G1329"
  station_trains:
    - "G6153"
    - "G6184"
    - "G6173"

  # 出发城市，比如深圳北，就填深圳就搜得到
  from_station: "邵阳"

  # 到达城市 比如深圳北，就填深圳就搜得到
  to_station: "深圳北"

  # 座位(list) 多个座位ex:
  # - "商务座"
  # - "一等座"
  # - "二等座"
  # - "特等座"
  # - "软卧"
  # - "硬卧"
  # - "硬座"
  # - "无座"
  # - "动卧"
  set_type:
  - "二等座"

  # 当余票小于乘车人，如果选择优先提交，则删减联系人和余票数一致在提交
  is_more_ticket: False

  # 乘车人(list) 多个乘车人ex:
  # - "张三"
  # - "李四"
  ticke_peoples:
    - ""

  # 12306登录账号(list)
  12306account:
    - user: "qqxin1011"
    - pwd: ""

# 加入小黑屋时间默认为5分钟，此功能为了防止僵尸票导致一直下单不成功错过正常的票，
ticket_black_list_time: 5

# 自动打码
is_auto_code: True

# 打码平台， 2 为若快平台（目前只支持若快平台打码，打码兔已经关闭）, 若快注册地址：http://www.ruokuai.com/client/index?6726
auto_code_type: 2

# 打码平台账号
auto_code_account:
  user: "931128603"
  pwd: ""

#  邮箱配置，如果抢票成功，将通过邮件配置通知给您
#  列举163
#  email: "xxx@163.com"
#  notice_email_list: "123@qq.com"
#  username: "xxxxx"
#  password: "xxxxx
#  host: "smtp.163.com"
#  列举qq  ，qq设置比较复杂，需要在邮箱-->账户-->开启smtp服务，取得授权码==邮箱登录密码
#  email: "xxx@qq.com"
#  notice_email_list: "123@qq.com"
#  username: "xxxxx"
#  password: "授权码"
#  host: "smtp.qq.com"
email_conf:
  is_email: True
  email: "931128603@qq.com "
  notice_email_list: "931128603@qq.com"
  username: "931128603"
  password: ""
  host: "smtp.qq.com"

# 是否开启 pushbear 微信提醒， 使用前需要前往 http://pushbear.ftqq.com 扫码绑定获取 send_key 并关注获得抢票结果通知的公众号
pushbear_conf:
  is_pushbear: False
  send_key: ""

# 是否开启cdn查询，可以更快的检测票票 1为开启，2为关闭
is_cdn: 1

# 下单接口分为两种，1 模拟网页自动捡漏下单（不稳定），2 模拟车次后面的购票按钮下单（稳如老狗）
order_type: 2

# 下单模式 1 为预售，整点刷新，刷新间隔0.1-0.5S, 然后会校验时间，比如12点的预售，那脚本就会在12.00整检票，刷新订单
#         2 是捡漏，捡漏的刷新间隔时间为0.5-3秒，时间间隔长，不容易封ip
order_model: 2

# 预售放票时间, 如果是捡漏模式，可以忽略此操作
open_time: '13:00:00'

# 是否开启代理, 0代表关闭， 1表示开始
# 开启此功能的时候请确保代理ip是否可用，在测试放里面经过充分的测试，再开启此功能，不然可能会耽误你购票的宝贵时间
# 使用方法：
# 1、在agency/proxy_list列表下填入代理ip
# 2、测试UnitTest/TestAll/testProxy 测试代理是否可以用
# 3、开启代理ip
is_proxy: 0


